Feature/native token
odradev/odra pull request #52
Opened 2022-10-12 14:24 UTC by kpob

See #36

2022-10-13 09:45 UTC, zie1ony requested changes

2022-10-13 09:45 UTC, zie1ony commented on core/src/contract_def.rs
> +    PublicPayable,
+1 for good naming :)

2022-10-13 09:45 UTC, zie1ony commented on lang/codegen/src/generator/common.rs
> +            odra::call_contract(&self.address, #entrypoint_name, &args, self.attached_value)
Shouldn't you set `self.attached_value` to `None` after those `call_contract` calls?

2022-10-13 09:45 UTC, zie1ony commented on lang/codegen/src/generator/module_impl/reference.rs
> +                    Self { address, attached_value: None }
`lang/codegen/src/generator/external_contract_item.rs` has very similar code. Could it be merged?

2022-10-13 09:45 UTC, zie1ony commented on lang/ir/src/attrs.rs
> +fn validate<I>(attrs: I) -> Result<(), syn::Error>
It would work on the reference. You would avoid cloning in  `validate(kinds.clone())?;`;

2022-10-13 09:45 UTC, zie1ony commented on lang/ir/src/attrs.rs
> +    use std::vec;
Is this needed?

2022-10-13 09:45 UTC, zie1ony commented on lang/ir/src/module_item/constructor.rs
> +        let full_sig = method.clone().sig;
```suggestion
        let full_sig = method.sig.clone();
```
?

2022-10-13 09:45 UTC, zie1ony commented on lang/ir/src/module_item/utils.rs
> +    let attached_value_check: Option<syn::Stmt> = match is_payable {
There is something wrong here. I think the whole function can be rewriten using simple `if else` statement.

2022-10-13 09:45 UTC, zie1ony commented on lang/ir/src/module_item/utils.rs
> +        stmts.insert(0, check);
Does this `insert` replaces first statement with `check` or appends to the front?

2022-10-13 09:45 UTC, zie1ony commented on mock_vm/src/mock_vm.rs
> +    contract_accounts: Arc<RwLock<ContractAccounts>>,
Try to put balances into `state` in `HashMap<Address, Balance>`.

2022-10-13 17:02 UTC, kpob commented on mock_vm/src/mock_vm.rs
> +    contract_accounts: Arc<RwLock<ContractAccounts>>,
You can look at it once again. Many changes were applied. All balances are kept on one hash map and restored similarly to the state (from a snapshot), callstack keeps not only the address but also the value attached to the call. Surprisingly, the code is much simpler now.

2022-10-14 07:14 UTC, kpob commented on lang/ir/src/module_item/utils.rs
> +        stmts.insert(0, check);
Puts in the specified position and shifts the remaining items.

2022-10-14 07:19 UTC, kpob commented on lang/codegen/src/generator/common.rs
> +            odra::call_contract(&self.address, #entrypoint_name, &args, self.attached_value)
I guess I should, good catch.

2022-10-14 07:38 UTC, kpob commented on lang/codegen/src/generator/common.rs
> +            odra::call_contract(&self.address, #entrypoint_name, &args, self.attached_value)
But the thing is, it implies all the functions must be mutable. If so, a user has to define a  contract ref as mutable but is not too intuitive.

2022-10-14 09:05 UTC, kpob commented on lang/ir/src/module_item/utils.rs
> +    let attached_value_check: Option<syn::Stmt> = match is_payable {
Rewritten. The original function is no longer altered. Each backend (mock VM, Casper) does the check on its side.

2022-10-17 07:28 UTC, zie1ony approved these changes

2022-10-17 07:32 UTC, merged